create database Book_music_store;
use Book_music_store;
create table author (Author_name varchar(20), Address varchar(20), url varchar(30),primary key(Author_name,Address));
create table publisher (Name varchar(20) primary key,Address varchar(20),Phone int,url varchar(30));
create table customer ( Name varchar(20),Address varchar(20),Email varchar(20) primary key,Phone int);
alter table customer add column cust_id int auto_increment unique;
alter table customer auto_increment=100;
create table book( Title varchar(10),Author_name varchar(20),Publiser_name varchar(20),Year int,Price int,ISBN int primary key,foreign key (Author_name) references author(Author_name),foreign key (Publiser_name) references publisher(Name));
create table warehouse(Code int primary key,ISBN int,Address varchar(30),phone_no int,foreign key(ISBN) references book(ISBN));
drop table music_cassete;
drop table compact_disk;
create table music_lable(Name varchar(20),location varchar(20),email varchar(20),phone int);
create table album(album_id varchar(10) primary key,album_name varchar(10),artist varchar(10),lable varchar(20));
create table music_cassete(product_id varchar(10) primary key,album_id varchar(10),price int,foreign key(album_id) references album(album_id));
create table compact_disk(product_id varchar(10) primary key,album_id varchar(10),price int,foreign key(album_id) references album(album_id));
create table distributor(Code int primary key,Name varchar(10),Address varchar(30),album_id varchar(10),phone_no int,foreign key(album_id) references album(album_id));